<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SmartStandards.KnowledgeManagement.AspNetCore</AssemblyName>
    <RootNamespace>KnowledgeManagement.SmartStandards</RootNamespace>
    <Deterministic>false</Deterministic>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ImportedNamespaces></ImportedNamespaces>
  </PropertyGroup>

  <!-- META DATA -->

  <PropertyGroup>
    <PackageId>KnowledgeManagement.AspNetCore</PackageId>
    <Description>KnowledgeManagement.AspNetCore</Description>
    <Product>KnowledgeManagement</Product>
    <PackageTags></PackageTags>
    <Company>(public domain)</Company>
    <Copyright>SmartStandards</Copyright>
    <Authors>SmartStandards</Authors>
    <!-- VERSION -->
    <Version>0.1.1</Version>
    <AssemblyVersion>0.1.1</AssemblyVersion>
    <FileVersion>0.1.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- ADDITIONAL ASSEMBLY-ATTRIBUTES -->
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>SourceContext</_Parameter1>
      <_Parameter2>KnowledgeManagement</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <!-- BUILD -->

  <PropertyGroup>
    <OutputPath>..\..\dist</OutputPath>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <DefineConstants>$(DefineConstants);NET_CORE;NET_8_;NET_10_;NET_10</DefineConstants>
    <NoWarn>$(NoWarn);1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <Target Name="_ResolveCopyLocalNuGetPkgXmls" AfterTargets="ResolveReferences">
    <ItemGroup>
      <!-- Copy also XML-Doc files from all PackageReferences to output dir -->
      <ReferenceCopyLocalPaths Include="@(ReferenceCopyLocalPaths->'%(RootDir)%(Directory)%(Filename).xml')" Condition="'%(ReferenceCopyLocalPaths.NuGetPackageId)'!='' and Exists('%(RootDir)%(Directory)%(Filename).xml')" />
    </ItemGroup>
  </Target>

  <!-- REFERENCES -->

  <ItemGroup>

    <!-- IMPORTANT: this package is made for the ASP.NET Core ecosystem ONLY -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <!--<PackageReference Include="SmartStandards.WebApiDependencies.net10.0" Version="10.0.14" />-->

    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
    
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="UJMW.DynamicController" Version="5.6.2" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KnowledgeManagement.net10.0\KnowledgeManagement.net10.0.csproj" />
  </ItemGroup>

  <!-- INCLUDEs and FILEs -->

  <Import Project="..\KnowledgeManagement.AspNetCore\KnowledgeManagement.AspNetCore.projitems" Label="Shared" />

</Project>