<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SmartStandards.KnowledgeManagement.Tests</AssemblyName>
    <RootNamespace>KnowledgeManagement.SmartStandards</RootNamespace>
    <Deterministic>false</Deterministic>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ImportedNamespaces></ImportedNamespaces>
  </PropertyGroup>

  <!-- META DATA -->

  <PropertyGroup>
    <PackageId>KnowledgeManagement.Tests</PackageId>
    <Description>KnowledgeManagement.Tests</Description>
    <Product>KnowledgeManagement</Product>
    <PackageTags></PackageTags>
    <Company>(public domain)</Company>
    <Copyright>SmartStandards</Copyright>
    <Authors>SmartStandards</Authors>
    <!-- VERSION -->
    <Version>0.1.3</Version>
    <AssemblyVersion>0.1.3</AssemblyVersion>
    <FileVersion>0.1.3</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- ADDITIONAL ASSEMBLY-ATTRIBUTES -->
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>SourceContext</_Parameter1>
      <_Parameter2>KnowledgeManagement</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <!-- BUILD -->

  <PropertyGroup>
    <OutputPath>..\..\dist</OutputPath>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <DefineConstants>$(DefineConstants);NET_CORE;NET_8_;NET_10_;NET_10</DefineConstants>
    <NoWarn>$(NoWarn);1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <!-- REFERENCES -->

  <ItemGroup>

    <PackageReference Include="MSTest" Version="3.11.1" />

    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />

    <PackageReference Include="SmartStandards.CyclicTriggering" Version="0.1.2" />
    <PackageReference Include="UJMW.DynamicClient" Version="5.6.2" />

    <PackageReference Include="SmartAmbience" Version="3.2.0" />
    <PackageReference Include="SmartAmbience.MvcSupport" Version="3.2.0" />
    <PackageReference Include="SmartStandards.AuthTokenHandling" Version="5.1.1" />
    <PackageReference Include="SmartStandards.Logging" Version="3.4.4" />
    <PackageReference Include="SmartStandards.Logging.Centralized" Version="3.4.4" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KnowledgeManagement.CommonProviders.net10.0\KnowledgeManagement.CommonProviders.net10.0.csproj" />
    <ProjectReference Include="..\..\src\KnowledgeManagement.DemoWebService\KnowledgeManagement.DemoWebService.csproj" />
    <ProjectReference Include="..\..\src\KnowledgeManagement.net10.0\KnowledgeManagement.net10.0.csproj" />
  </ItemGroup>

  <!-- INCLUDEs and FILEs -->

</Project>